### ISSUE TITLE
Unable to login - Timeout error

### ISSUE THREAD

**Issue by arsaboo** [itsjafer/schwab-api#33]
I tried the script both on Colab and my local computer, and on both places, I ran into the following error:

```bash
(base) C:\Users\arsab\Desktop\Jupyter>python schwab.py
Logging into Schwab
Traceback (most recent call last):
  File "C:\Users\arsab\anaconda3\lib\site-packages\schwab_api\authentication.py", line 124, in login
    self.page.frame(name=login_frame).press("[placeholder=\"Password\"]", "Enter")
  File "C:\Users\arsab\anaconda3\lib\site-packages\playwright\_impl\_sync_base.py", line 79, in __exit__
    self._event.value
  File "C:\Users\arsab\anaconda3\lib\site-packages\playwright\_impl\_sync_base.py", line 59, in value
    raise exception
  File "C:\Users\arsab\anaconda3\lib\site-packages\playwright\_impl\_frame.py", line 208, in continuation
    event = await wait_helper.result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for navigation until 'load'
============================================================

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\arsab\Desktop\Jupyter\schwab.py", line 17, in <module>
    logged_in = api.login(
  File "C:\Users\arsab\anaconda3\lib\site-packages\schwab_api\authentication.py", line 126, in login
    raise Exception("Login was not successful; please check username and password")
Exception: Login was not successful; please check username and password
```

**Comment by itsjafer** [comment]
I would recommending confirming your login and TOTP details
